#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
	CREATE USER ${POSTGRES_NEXTCLOUD_USER};
	ALTER USER ${POSTGRES_NEXTCLOUD_USER} WITH PASSWORD '${POSTGRES_NEXTCLOUD_PASSWORD}';
	CREATE DATABASE ${POSTGRES_NEXTCLOUD_DB} WITH OWNER = ${POSTGRES_NEXTCLOUD_USER};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_NEXTCLOUD_DB} TO ${POSTGRES_NEXTCLOUD_USER};
EOSQL

